version: "3.1"
services:

  gluon-layer1:
    image: tearust/tea-layer1:gluon-0.2.0
    container_name: gluon-layer1
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - .layer1:/root/.local
    command: bash -c "tea-layer1 --dev --alice --tmp --ws-port 9944 --rpc-port 9933 --unsafe-ws-external --unsafe-rpc-external --rpc-cors all -lwarn"
        
    
  gluon-webapp:
    image: tearust/gluon-webapp:0.1
    container_name: gluon-webapp
    ports:
      - 3000:80
    environment: 
      - NODE_ENV=production
      - VUE_APP_LAYER1_URL=ws://127.0.0.1:9944
      - VUE_APP_LAYER1_HTTP=http://127.0.0.1:9933
